import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  // Ignore build output, deps and the Rust side
  {
    ignores: [
      "dist",
      "node_modules",
      "src-tauri",
      "coverage",
      "*.config.js",
      "*.config.ts",
      // Generated by @tanstack/router-plugin — never hand-edited
      "src/routeTree.gen.ts",
    ],
  },

  // Base JS + TS recommended
  js.configs.recommended,
  ...tseslint.configs.recommended,

  // App source (browser env)
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": "warn",
      // Architecture guard: only designated boundary files may talk to Tauri plugins.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@tauri-apps/api",
              message:
                "Only src/core/ipc.ts may import @tauri-apps/api. Go through a repository.",
            },
            {
              name: "@tauri-apps/plugin-updater",
              message:
                "Only src/features/updater/data/repositories/tauri-updater.repository.ts may import @tauri-apps/plugin-updater.",
            },
            {
              name: "@tauri-apps/plugin-process",
              message:
                "Only src/features/updater/data/repositories/tauri-updater.repository.ts may import @tauri-apps/plugin-process.",
            },
          ],
          patterns: ["@tauri-apps/api/*"],
        },
      ],
    },
  },

  // Allow the Tauri boundary + tests to import @tauri-apps/* directly
  {
    files: [
      "src/core/ipc.ts",
      "src/features/updater/data/repositories/tauri-updater.repository.ts",
      "src/test/**/*.{ts,tsx}",
      "src/**/*.{test,spec}.{ts,tsx}",
    ],
    rules: {
      "no-restricted-imports": "off",
    },
  },

  // MUST be last: disable formatting rules so Prettier owns formatting
  prettier,
);
