/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCommutesIndexRouteImport } from './routes/_authenticated/commutes/index'
import { Route as AuthenticatedWorkHoursDayRouteImport } from './routes/_authenticated/work-hours/$day'
import { Route as AuthenticatedCommutesNewRouteImport } from './routes/_authenticated/commutes/new'
import { Route as AuthenticatedCommutesCommuteIdEditRouteImport } from './routes/_authenticated/commutes/$commuteId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommutesIndexRoute =
  AuthenticatedCommutesIndexRouteImport.update({
    id: '/commutes/',
    path: '/commutes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkHoursDayRoute =
  AuthenticatedWorkHoursDayRouteImport.update({
    id: '/work-hours/$day',
    path: '/work-hours/$day',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommutesNewRoute =
  AuthenticatedCommutesNewRouteImport.update({
    id: '/commutes/new',
    path: '/commutes/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommutesCommuteIdEditRoute =
  AuthenticatedCommutesCommuteIdEditRouteImport.update({
    id: '/commutes/$commuteId/edit',
    path: '/commutes/$commuteId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/commutes/new': typeof AuthenticatedCommutesNewRoute
  '/work-hours/$day': typeof AuthenticatedWorkHoursDayRoute
  '/commutes/': typeof AuthenticatedCommutesIndexRoute
  '/commutes/$commuteId/edit': typeof AuthenticatedCommutesCommuteIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/commutes/new': typeof AuthenticatedCommutesNewRoute
  '/work-hours/$day': typeof AuthenticatedWorkHoursDayRoute
  '/commutes': typeof AuthenticatedCommutesIndexRoute
  '/commutes/$commuteId/edit': typeof AuthenticatedCommutesCommuteIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/commutes/new': typeof AuthenticatedCommutesNewRoute
  '/_authenticated/work-hours/$day': typeof AuthenticatedWorkHoursDayRoute
  '/_authenticated/commutes/': typeof AuthenticatedCommutesIndexRoute
  '/_authenticated/commutes/$commuteId/edit': typeof AuthenticatedCommutesCommuteIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/commutes/new'
    | '/work-hours/$day'
    | '/commutes/'
    | '/commutes/$commuteId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/'
    | '/commutes/new'
    | '/work-hours/$day'
    | '/commutes'
    | '/commutes/$commuteId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/commutes/new'
    | '/_authenticated/work-hours/$day'
    | '/_authenticated/commutes/'
    | '/_authenticated/commutes/$commuteId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commutes/': {
      id: '/_authenticated/commutes/'
      path: '/commutes'
      fullPath: '/commutes/'
      preLoaderRoute: typeof AuthenticatedCommutesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/work-hours/$day': {
      id: '/_authenticated/work-hours/$day'
      path: '/work-hours/$day'
      fullPath: '/work-hours/$day'
      preLoaderRoute: typeof AuthenticatedWorkHoursDayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commutes/new': {
      id: '/_authenticated/commutes/new'
      path: '/commutes/new'
      fullPath: '/commutes/new'
      preLoaderRoute: typeof AuthenticatedCommutesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commutes/$commuteId/edit': {
      id: '/_authenticated/commutes/$commuteId/edit'
      path: '/commutes/$commuteId/edit'
      fullPath: '/commutes/$commuteId/edit'
      preLoaderRoute: typeof AuthenticatedCommutesCommuteIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCommutesNewRoute: typeof AuthenticatedCommutesNewRoute
  AuthenticatedWorkHoursDayRoute: typeof AuthenticatedWorkHoursDayRoute
  AuthenticatedCommutesIndexRoute: typeof AuthenticatedCommutesIndexRoute
  AuthenticatedCommutesCommuteIdEditRoute: typeof AuthenticatedCommutesCommuteIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCommutesNewRoute: AuthenticatedCommutesNewRoute,
  AuthenticatedWorkHoursDayRoute: AuthenticatedWorkHoursDayRoute,
  AuthenticatedCommutesIndexRoute: AuthenticatedCommutesIndexRoute,
  AuthenticatedCommutesCommuteIdEditRoute:
    AuthenticatedCommutesCommuteIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
